# Estimates of the sensitivity
In this notebook, we estimates the sensitivities for LETO (Line Emission Terahertz Observatory) and save the data to be plotted and analysed later on. First, we import the Python packages

In [1]:
import numpy as np

import astropy.units as u
from astropy.table import Table
from astropy.cosmology import Planck13, FlatLambdaCDM

from telescope_estimator import LuminEstimator

cosmo = FlatLambdaCDM(H0=70, Om0=0.3, Tcmb0=2.725)

## Reading and pre-processing data

We read the pySIDES original data

In [2]:
# This file is very large, so we recommend downloading the file yourself
cat = Table.read('pySIDES_from_original.fits', format='fits')

We also read the coefficients calculated for the paper (It is possible to also select the case where only HII regions are taken into account)

In [3]:
# Change the file that you want to use manually or uncomment the respective lines in the notebook
# estimated_linreg = Table.read('../data/raw//coeff_linreg.csv', format='ascii.csv')
# estimated_linreg = Table.read('../data/raw//coeff_linreg_HII.csv', format='ascii.csv') # In case HII
estimated_linreg = Table.read('../data/interim/coeff_MLPreg.csv',
                              format='ascii.csv')

# Dictionaries to create the analog of the lines names
linreg_lines = {'CII158': 'logLCII', 'NIII': 'logLNIII_57',
                'NII205': 'logLNII_205', 'NII122': 'logLNII_122',
                'OI145': 'logLOI_145',  'OI63': 'logLOI_63',
                'OIII88': 'logLOIII_88', 'OIII52': 'logLOIII_51'}
inv_linreg_lines = {v: k for k, v in linreg_lines.items()}

We calculate the log(1+z) and log(SFR) from the SIDES catalog. With this we can estimate the expected line luminosity for the galaxies in the catalog.

In [4]:
logz = np.log10(1 + cat['redshift'])
logsfr = np.log10(cat['SFR'])

# for line in linreg_lines:
#     row = np.where(estimated_linreg['line'] == linreg_lines[line])[0]
#     cat['L'+line] = (estimated_linreg['Intercept'][row] +
#                      estimated_linreg['cSFR'][row]*logsfr +
#                      estimated_linreg['clogz'][row]*logz + estimated_linreg['cSFRlogz'][row]*logz*logsfr)

for line in linreg_lines:
    row = np.where(estimated_linreg['line'] == linreg_lines[line])[0]
    cat['L'+line] = (estimated_linreg['Intercept'][row] +
                     estimated_linreg['cSFR'][row]*logsfr +
                     estimated_linreg['cSFR2'][row]*logsfr*logsfr +
                     estimated_linreg['clogz'][row]*logz +
                     estimated_linreg['cSFRlogz'][row]*logz*logsfr)

<ipython-input-4-244383a5b828>:2: RuntimeWarning: divide by zero encountered in log10
  logsfr = np.log10(cat['SFR'])
<ipython-input-4-244383a5b828>:12: RuntimeWarning: invalid value encountered in add
  cat['L'+line] = (estimated_linreg['Intercept'][row] +


## Using the estimator to calculate the bands sensitivies
We redefine the class for the LETO estimator to start our calculations

In [5]:
LETO_estimator = LuminEstimator()

We run a simple verification to verify is working

In [6]:
# Inputs
HTIME = 1  # In hours
# bw = 18.75 * u.MHz # bandwidth
line_width = 12 * u.km/u.s
int_time = 3600*HTIME * u.s
NPOL = 1.4  # 2 for polarised measurement

list_int_time = [int_time, int_time*10, int_time*100, int_time*1000]

LETO_estimator.estimate_flux(line_width, list_int_time, NPOL)

# Print as an example
LETO_estimator.retrive_lum(Planck13.luminosity_distance(0.2))

[array([6.20381168, 7.22619492, 7.81754341, 7.86823446, 7.9015483 ,
        7.95230346, 7.04639136, 7.1645728 ]),
 array([5.70381168, 6.72619492, 7.31754341, 7.36823446, 7.4015483 ,
        7.45230346, 6.54639136, 6.6645728 ]),
 array([5.20381168, 6.22619492, 6.81754341, 6.86823446, 6.9015483 ,
        6.95230346, 6.04639136, 6.1645728 ]),
 array([4.70381168, 5.72619492, 6.31754341, 6.36823446, 6.4015483 ,
        6.45230346, 5.54639136, 5.6645728 ])]

In [8]:
LETO_estimator.table

<Table length=8>
 Species  Wavelength ...       Flux 100h              Flux 1000h      
            micron   ...         W / m2                 W / m2        
  str32    float64   ...        float64                float64        
--------- ---------- ... ---------------------- ----------------------
 CI [608]      609.3 ...  5.004327619134812e-21 1.5825073434153628e-21
 CI [370]      370.6 ...  5.269009405837513e-20 1.6662070735297034e-20
NII [205]      205.3 ...  2.056257324880769e-19  6.502456602028049e-20
CII [158]     157.68 ... 2.3108327672473595e-19  7.307494836251398e-20
 OI [145]     145.53 ...  2.495067819018311e-19  7.890097224686645e-20
NII [122]      121.8 ... 2.8043842289479085e-19  8.868241597730498e-20
 OH [119]      119.0 ...  3.482774966623412e-20 1.1013501472346885e-20
  OI [63]      63.18 ...  4.572006725722333e-20 1.4457954730891308e-20

Create dictionaries to work with the estimators

In [10]:
list_lines = [inv_linreg_lines[line] for line in estimated_linreg['line'].data]
disp = {}
for A, B in zip(list_lines, estimated_linreg['sigma'].data):
    disp[A] = B

wave_lines = {'OIII52': 51.81, 'NIII': 57.34, 'OI63': 63.18,
              'OIII88': 88.36, 'NII122': 121.8, 'OI145': 145.53,
              'CII158': 157.68, 'NII205': 205.3}
# wave_lines = {'OIII88': 88.36,
#               'CII158': 157.68}

Finally, we estimate the lines that we could observe with the configuration of the telescope

In [11]:
total_array = []
bands_to_use = [False, True, True, True, True, True, False, False]
# bands_to_use = [False, True, True, False, False, False, False, False]
for line in wave_lines:
    for irow, row in enumerate(LETO_estimator.table[bands_to_use]):
        redsh = (row['Wavelength']-wave_lines[line])/wave_lines[line]
        freq = (wave_lines[line] * u.micron).to(u.GHz,
                                                equivalencies=u.spectral()).value
        if redsh <= -0.05:
            print('Local Universe')
        else:
            lum_min = np.array(LETO_estimator.retrive_lum(
                Planck13.luminosity_distance(redsh))).T[bands_to_use][irow]
            lum_min = np.log10(10**lum_min / (1+redsh))
            flux_min = []
            for col in LETO_estimator.table.colnames:
                if col.startswith('Flux'):
                    if col.endswith('h') or col.endswith('x'):
                        flux_min.append(
                            LETO_estimator.table[bands_to_use][col][irow])
            flux_min = np.array(flux_min)
            band_z = (row['Frequency'] + row['Range'],
                      row['Frequency'] - row['Range'])
            redsh1 = ((freq - band_z[0]) / band_z[0])
            redsh2 = ((freq - band_z[1]) / band_z[1])
            secl = cat[np.logical_and.reduce(
                [cat['redshift'] > redsh1, cat['redshift'] < redsh2, cat['SFR'] > 0])]
            print(redsh, line, row['Species'],
                  lum_min, flux_min, redsh1, redsh2)
            allcounts = []
            for iterat in range(500):
                # Because SIDEs is 2deg^2
                sample = (secl.to_pandas().sample(frac=0.5))
                rand_lum = disp[line] * \
                    (2*np.random.random(size=len(sample)) - 1)
                counts, bins = np.histogram(sample['L'+line] + rand_lum,
                                            bins=np.linspace(5, 12, 71))
                allcounts.append(counts)
#             print('Estimated', np.median(allcounts, axis=0),
#                   np.std(allcounts, axis=0),
#                   np.percentile(allcounts, 75, axis=0))
            counts = np.mean(allcounts, axis=0)  # maybe median?
            er_counts = np.std(allcounts, axis=0)
            poisson_error = np.sqrt(counts)
            per25_counts = np.percentile(allcounts, 25, axis=0)
            per75_counts = np.percentile(allcounts, 75, axis=0)
            total_array.append([line, row['Species'], redsh, redsh1, redsh2, list_int_time,
                                lum_min, flux_min, bins, counts, er_counts, poisson_error,
                                per25_counts, per75_counts])
#             print(total_array)

6.153059254970083 OIII52 CI [370] [9.92994282 9.42994282 8.92994282 8.42994282] [5.26900941e-19 1.66620707e-19 5.26900941e-20 1.66620707e-20] 6.014322847019202 6.2973945426853835
2.9625554912179117 OIII52 NII [205] [10.02812602  9.52812602  9.02812602  8.52812602] [2.05625732e-18 6.50245660e-19 2.05625732e-19 6.50245660e-20] 2.919608678370764 3.0064538591904264
2.0434279096699477 OIII52 CII [158] [9.80269684 9.30269684 8.80269684 8.30269684] [2.31083277e-18 7.30749484e-19 2.31083277e-19 7.30749484e-20] 2.018029914796303 2.069257002093082
1.8089171974522291 OIII52 OI [145] [9.74137207 9.24137207 8.74137207 8.24137207] [2.49506782e-18 7.89009722e-19 2.49506782e-19 7.89009722e-20] 1.7872685571454006 1.8309047589711014
1.3508975101331788 OIII52 NII [122] [9.55761694 9.05761694 8.55761694 8.05761694] [2.80438423e-18 8.86824160e-19 2.80438423e-19 8.86824160e-20] 1.3357142067357113 1.3662795031509638
5.463201953261248 NIII CI [370] [9.85379567 9.35379567 8.85379567 8.35379567] [5.26900941e-19

We organize the table and we check the results

In [12]:
All = Table(np.array(total_array), names=['Line', 'Band', 'z', 'z_min', 'z_max',
                                          'Int_times',
                                          'Lums_min', 'Fluxes_min',
                                          'Lum_bins', 'mean_counts',
                                          'std', 'poisson_err', 'p25', 'p75'])

<ipython-input-12-80d6d5ad6f74>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  All = Table(np.array(total_array), names=['Line', 'Band', 'z', 'z_min', 'z_max',


In [13]:
All[-2]

<Row index=32>
 Line    Band           z                z_min             z_max                                              Int_times                                                         Lums_min                                           Fluxes_min                                                                                                                                                                                                           Lum_bins                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     mean_counts                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          std                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      poisson_err                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  p25                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   p75                                                                                                                                                        

Finally, we save the file to further analysis

In [14]:
# np.save('../data/processed/NcountsMay_SIDES_LETO_percentiles_poisson_HII', All.as_array())
# np.save('../data/processed/NcountsMay_SIDES_LETO_percentiles_poisson', All.as_array())
np.save('../data/processed/NcountsMay_SIDES_LETO_percentiles_poisson_MLP', All.as_array())

##### Notebook information

In [15]:
%load_ext watermark
%watermark -a "Andres Ramos" -d -v -m
print('Specific Python packages')
%watermark -iv -w 

Author: Andres Ramos

Python implementation: CPython
Python version       : 3.8.3
IPython version      : 7.16.1

Compiler    : GCC 7.3.0
OS          : Linux
Release     : 3.10.0-1160.59.1.el7.x86_64
Machine     : x86_64
Processor   : x86_64
CPU cores   : 8
Architecture: 64bit

Specific Python packages
astropy : 5.0
numpy   : 1.22.1
autopep8: 1.5.7
json    : 2.0.9

Watermark: 2.2.0

